### ISSUE TITLE
[Bug]: Caching bin dir does not work

### ISSUE THREAD

**Issue by mbechto** [kubeshop/setup-testkube#5]
### Contact Details

matthias.bechtold@techspace.de

### What happened?

Tried to use the action in self-hosted GHA runners (version 2.311.0), couldn't get it to work.

Looking at the error, the problem may be that it tries to cache the whole `/usr/local/bin` dir. A probable solution would be to just cache the extracted tar contents. For example [actions/setup-go](https://github.com/actions/setup-go/blob/cdcb36043654635271a94b9a6d1392de5bb323a7/src/installer.ts#L251) does this as well.

### Version

1.0.0 (Default)

### Relevant log output

```shell
Detected mode: kubectl connection. To use Cloud connection instead, provide your 'organization', 'environment' and 'token'.
Architecture: x86_64 (x86_64)
System: Linux (Linux)
Binary path: /usr/local/bin
kubectl: detected.
Forcing "1.17.22 version...
Downloading the artifact from "https://github.com/kubeshop/testkube/releases/download/v1.17.22/testkube_1.17.22_Linux_x86_64.tar.gz"...
/usr/bin/tar xz --warning=no-unknown-keyword --overwrite -C /usr/local/bin -f /home/runner/actions-runner/_work/_temp/decc21af-5db3-4fa9-ab5d-484edfa703d6
Extracted CLI to /usr/local/bin/kubectl-testkube.
/home/runner/actions-runner/_work/_actions/kubeshop/setup-testkube/main/dist/index.js:2783
            throw new Error(`no such file or directory: ${source}`);
                  ^

Error: no such file or directory: /usr/local/bin/invoke_tests
    at Object.<anonymous> (/home/runner/actions-runner/_work/_actions/kubeshop/setup-testkube/main/dist/index.js:2783:19)
    at Generator.next (<anonymous>)
    at fulfilled (/home/runner/actions-runner/_work/_actions/kubeshop/setup-testkube/main/dist/index.js:2751:58)
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by mbechto** [comment]
I can confirm that it also works in our setup now (using 12a1cb4).
